[build]
target = "x86_64-blog_os.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[target.'cfg(target_env="msvc")']
rustflags = [
    "-C", "link-args=/ENTRY:_start /SUBSYSTEM:console",
]

[target.'cfg(target_env="gnu")']
rustflags = [
    "-C", "link-arg=-e _start",
]
